apiVersion: argoproj.io/v1alpha1
kind: Service
metadata:
  name: argocd-helloworld
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my_channel
spec:
  selector:
    app: argocd-helloworld
  ports:
    - port: 80
      targetPort: 80
