apiVersion: v1
kind: Service
metadata:
  name: argocd-helloworld
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd #Slack Channel name
spec:
  selector:
    app: argocd-helloworld
  ports:
    - port: 80
      targetPort: 80
